name: digital-lommebok-issuer
networks:
  digital-lommebok:
    name: digital-lommebok

services:
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      start_period: 3s
      timeout: 2s
      retries: 20
    ports:
      - "9262:6379"
    networks:
      - digital-lommebok
    command: redis-server --maxmemory-policy allkeys-lru

  byob-service:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      spring_profiles_active: docker
      _JAVA_OPTIONS: "-XX:+IgnoreUnrecognizedVMOptions -XX:UseSVE=0 -Dotel.metrics.exporter=none -Dotel.traces.exporter=none -Dotel.span.exporter=none -Dotel.logs.exporter=none"
    ports:
      - "9296:9296"
      - "9297:9297"
    networks:
      - digital-lommebok
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/tomcat/webapps/
        java -javaagent:opentelemetry-javaagent.jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9297 -jar application.jar
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9296/health/readiness || exit 1
      interval: 15s
      start_period: 5s
      timeout: 5s
      retries: 20
