---
server:
  port: 9296

management:
  server:
    port: 9296
  endpoint:
    health:
      show-details: always

spring:
  application:
    environment: docker

  data:
    redis:
      host: localhost
      port: 6379

byob-service:
  api_key: my-not-so-secret-token
